# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'OnePiece' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for OnePiece
pod 'SnapKit'
pod 'Then'
pod 'Moya'
pod 'SwiftKeychainWrapper'
pod 'TagListView'

end
